sAdmin = {}
sAdmin.Config = {
    DefaultGroup = "user",
    KeyOpenMenu = "F9",
    KeyNoclip = "F10",
    Debug = false,
    Print = {
        DefaultPrefix = "[^4sAdmin^7]",
        DebugPrefix = "[^4sAdmin^7][^3Debug^7]"
    },

    Perms = {

        AccesCat = {
            ["interaction_perso"] = {

                ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["gerant"] = true,
                ["fondateur"] = true,
            },
            ["interaction_vehicle"] ={

                ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["gerant"] = true,
                ["fondateur"] = true,
            },
            ["report_menu"] = {

                ["animateur"] = false,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["gerant"] = true,
                ["fondateur"] = true,
            },
            ["interaction_players"] = {

                ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["gerant"] = true,
                ["fondateur"] = true,
            },
            ["action_dispo"] = {

                ["animateur"] = true,
                ["helpeur"] = true,
                ["moderateur"] = true,
                ["admin"] = true, 
                ["gerant"] = true,
                ["fondateur"] = true,
            },
            ["interaction_cardinal"] = {

                ["animateur"] = false,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = false,
                ["gerant"] = false,
                ["fondateur"] = true,
            },
            ['show_staffList'] = {
                ["animateur"] = false,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = false,
                ["gerant"] = true,
                ["fondateur"] = false,
            },
            ['option_serveur'] = {
                ["animateur"] = true,
                ["helpeur"] = false,
                ["moderateur"] = false,
                ["admin"] = true,
                ["gerant"] = true,
                ["fondateur"] = true,
            },
        },
        Buttons = {
            ["report_menu"] = {
                ["action_teleportation"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["action_player"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["sanction_player"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            },
            ["interaction_players"] = {
                ["action_teleportation"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["action_player"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["sanction_player"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            },
            ["cat_persoMenu"] = {
                ["noclip"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["invisibleMonde"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["show_gamertags"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                     ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["report_info"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                     ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["report_sound"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                     ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["teleport_waypoint"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["tache_sang"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["spawn_props"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            },
            ["cat_vehMenu"] = {
                ["repairVehicle"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["clearVehicle"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["freezeVehicle"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["returnVehicle"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["upgradeVehicules"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            },
            ["cat_playersActions"] = {
                ["screen"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["goto"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["wipe"] = {

                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["bring"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["tpparkingcentral"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["freeze"] = {
    
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["sendMess"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["spec"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true,
                    ["gerant"] = true,                  
                    ["fondateur"] = true,
                },
                ["revive"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                   
                    ["fondateur"] = true,
                },
                ["heal"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                   
                    ["fondateur"] = true,
                },
                ["kick"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                   
                    ["fondateur"] = true,
                },
                ["jail"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                   
                    ["fondateur"] = true,
                },
                ["ban"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                  
                    ["fondateur"] = true,
                },
                ["kill"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                  
                    ["fondateur"] = true,
                },
                ["warn"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,                  
                    ["fondateur"] = true,
                },
                
                ["showInventory"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["tache_sang_player"] = {
                    ["animateur"] = true,
                    ["helpeur"] = true,
                    ["moderateur"] = true,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["giveMoney"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["giveItem"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            },
            ["cat_cardinalActions"] = {
                ["giveVehicle"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["giveMoney"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["giveItem"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["giveWeapon"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["clearloadout"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            }, 
            ["action_dispo"] = {
                ["spawnVehicle"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["peds"] = {
                    ["animateur"] = false,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true, 
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            },
            ["option_serveur"] = {
                ["jobs"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["jobsinfos"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["items_list"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["change_weight_item"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["delete_item"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["eletriciter_ville"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["purge"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["gestion_staff"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["add_staff"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["modif_staff_role"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["staff_list"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["delete_staff"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["annonce"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["tp_all"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["revive_all"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
                ["heal_all"] = {
                    ["animateur"] = true,
                    ["helpeur"] = false,
                    ["moderateur"] = false,
                    ["admin"] = true,
                    ["gerant"] = true,
                    ["fondateur"] = true,
                },
            }
        }
    }
}